name: Comply Scheduler
description: Run comply scheduler for your compliance repo
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  jira_username:
    required: false
    description: Username for JIRA account
  jira_password:
    required: false
    description: Password (or API token) for JIRA account
