name: Comply Scheduler
description: Run comply scheduler for your compliance repo
runs:
  image: "docker://strongdm/comply:latest"
  entrypoint: comply scheduler
inputs:
  jira_username:
    required: false
    description: Username for JIRA account
  jira_password:
    required: false
    description: Password (or API token) for JIRA account
