name: Ticket Scheduler

# on:
#   schedule:
#     - cron: "*/10 * * * *"

on: push

jobs:
  scheduler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: .github/actions/scheduler
