name: Ticket Scheduler

# on:
#   schedule:
#     - cron: "*/10 * * * *"

on: push

jobs:
  scheduler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/scheduler
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ["scheduler"]
          jira_username: ${{ secrets.JIRA_USERNAME }}
          jira_password: ${{ secrets.JIRA_PASSWORD }}
